name: pbo_backbones
channels:
  - pytorch
  - pyg
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.8.0
  - ampl-mp=3.1.0
  - anyio=3.7.1
  - argon2-cffi=21.1.0
  - asttokens=2.4.1
  - attrs=24.2.0
  - babel=2.16.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2024.8.30
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cloudpickle=3.0.0
  - colorlog=6.9.0
  - comm=0.2.2
  - cppad=20220000.4
  - cryptography=37.0.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.4.4
  - ffmpeg=4.2.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2021.4.0
  - ipopt=3.14.8
  - ipykernel=6.29.5
  - ipython=8.12.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - jedi=0.19.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter=1.1.1
  - jupyter_client=7.3.4
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_server=1.24.0
  - jupyterlab=3.5.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.13
  - kiwisolver=1.4.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20210910
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=12.1.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mako=1.2.3
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.7
  - metis=5.1.0
  - mistune=3.0.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - munkres=1.1.4
  - nbclassic=1.1.0
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.3
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=2.8.4
  - notebook=6.5.7
  - notebook-shim=0.2.4
  - numexpr=2.8.3
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openh264=2.1.1
  - openssl=1.1.1w
  - optuna=4.2.1
  - packaging=21.3
  - pandas=1.4.3
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre=8.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.21
  - pyg=2.0.4
  - pygments=2.18.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyscipopt=4.2.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.20.0
  - python-louvain=0.15
  - python_abi=3.8
  - pytorch=1.10.2
  - pytorch-cluster=1.6.0
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.13
  - pytorch-spline-conv=1.2.1
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=25.1.2
  - qt=5.9.7
  - readline=8.1.2
  - referencing=0.35.1
  - requests=2.28.1
  - rpds-py=0.10.6
  - scikit-learn=1.1.1
  - scip=8.0.1
  - scipy=1.8.1
  - scotch=6.0.9
  - send2trash=1.8.3
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlalchemy=1.3.24
  - sqlite=3.38.5
  - stack_data=0.6.2
  - submitit=1.5.2
  - tbb=2021.5.0
  - terminado=0.18.1
  - threadpoolctl=2.2.0
  - tinycss2=1.4.0
  - tk=8.6.12
  - tomli=2.0.2
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.14.3
  - typing_extensions=4.1.1
  - unixodbc=2.3.9
  - urllib3=1.26.9
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.37.1
  - widgetsnbextension=4.0.13
  - x264=1!157.20191217
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
      - gurobipy==9.5.2
      - torcheval==0.0.7
